% MATLAB Editor Run Commands
% @version 4
% It is recommended that you do not edit this file directly, but use the
% Run button. Changes made to comments that exist outside of a
% configuration will not be saved.

%% @name discunit
%  @associatedFile /MATLAB Drive/discunit.m
%  @mostRecentlyActioned true
%  @uniqueId 07892ABD

discunit

%% @name discSinu
%  @associatedFile /MATLAB Drive/discSinu.m
%  @mostRecentlyActioned true
%  @uniqueId 0A7C15AD

discSinu

